### ISSUE TITLE
bluetooth connection error

### ISSUE THREAD

**Issue by djbr1** [Links2004/x6100-armbian#1]
1) Exception shown at Desktop after startup
Failed to apply network settings
You might not be able to connect to the Bluetooth network via this machine
org.freedesktop.DBus.Python.dbus.exceptions.DBusException: Not authorized

2) Connection to paired bluetooth device (handsfree or audio sink) does not work, error is:
"Connection Failed: blueman.bluez.errors.DBusFailedError: Protocol not available..."

73
hb9txb

**Comment by Links2004** [comment]
fixed by updating to debian sid.
