### ISSUE TITLE
CAT serial port

### ISSUE THREAD

**Issue by djbr1** [Links2004/x6100-armbian#6]
Hi 

please check how CAT port is implemented in[ wspr spotter:](https://github.com/sstjohn/x6100-wspr/blob/main/spotter-loop.py)

Beside qt gui app restart at script invocation, it works seamlessly - changes band every couple of minutes without interruption of qt gui,  frequency on gui is updated accordingly.

```
def redirect_qt_app():
    os.rename("/dev/ttyS2", "/dev/ttyS2.old")
    try:
        tnt0_stat = os.lstat("/dev/tnt0")
        newdev = os.makedev(os.major(tnt0_stat.st_rdev), os.minor(tnt0_stat.st_rdev))
        os.mknod("/dev/ttyS2", tnt0_stat.st_mode, newdev)
        os.system("/etc/init.d/S99userappstart restart")
        sleep(10)
        yield None
    finally:
        os.rename("/dev/ttyS2.old", "/dev/ttyS2")
        os.system("/etc/init.d/S99userappstart restart")
```

**Comment by Links2004** [comment]
Next build will come with network CAT and rigctld on the device.

I only need to sort out how to keep the USB-C working,
since there will be someone still using a cable.
