### ISSUE TITLE
Unable to boot Armbian on internal battery

### ISSUE THREAD

**Issue by W5DMH** [Links2004/x6100-armbian#9]
I can boot the x6100 OS when on internal battery no problem. When I attempt to boot with Armbian (regardless of button 1, 2 or 3) the radio crashes after the first few boot up lines and then powers off. 

This is a brand new radio, it has not been charged the obligatory 4 x 8hr charges yet and is only showing 7.8v when fully charged, is this potentially the cause?

**Comment by Links2004** [comment]
interesting, I have two x6100 and non of them ever has done this.

since the Internal OS is booting fine its most likely SD card related.
can you verify the SD card to see if the data is written correctly?

the SoC / display can work with the Battery and RF components disconnected so its not likely that the battery is the problem.

the SoC can be powered by the USB-C "DEV" port, so if you plug a Phone charger in there and its still happening then its for sure not a power problem.

**Comment by W5DMH** [comment]
> interesting, I have two x6100 and non of them ever has done this.
> 
> since the Internal OS is booting fine its most likely SD card related. can you verify the SD card to see if the data is written correctly?
> 
> the SoC / display can work with the Battery and RF components disconnected so its not likely that the battery is the problem.
> 
> the SoC can be powered by the USB-C "DEV" port, so if you plug a Phone charger in there and its still happening then its for sure not a power problem.

The SD card is fine as I can boot Armbian without a problem when I have external power connected. 
I am going to try depleting the internal battery and recharging it a few times until it shows the appropriate voltage and then try booting Armbian from the internal battery again and see what happens. 
I'm honestly a little fearful of plugging power into the USB-C port and trying to boot.

**Comment by Links2004** [comment]
if you connect your X6100 to a PC its providing power too ;)
but getting the battery indicator to show the correct voltage is a good first step.

**Comment by W5DMH** [comment]
Good point, I had not consider that the computer has power on the USB-C connection, however I am using a USB-C loop from Host to Dev for running JS8Call on Armbian :) 
Thanks for your hard work and diligence on this project, you may have singlehandedly cause a shift in the direction of Amateur Radio, this is cool factor 11!

**Comment by W5DMH** [comment]
So the obligatory 4 charges are now complete and I still cannot boot Armbian from the internal battery. I get about 10 lines into the Armbian boot up and it crashes and powers off. I did ensure the charging was turned off, I turned off WIFI on the x6100. My internal batteries last about 3 hours on receive so I don't think it's a battery issue per say but it might be a current draw issue? 
I can plug in a 13.8v power supply and immediately boot up Armbian with no problem. 
I will try a good USB-C power source and see what happens now. 

Update:  I booted up with a 2amp USB-C power source in the USB-DEV port and it booted up fine for Armbian but the x6100 OS did not boot up, kind of weird but maybe that makes sense to you.

**Comment by Links2004** [comment]
unfortunately this is very strange, with 2A on USB-C the SoC can for sure Boot with out any battery at all.
may your unit has some sort of detect.

what are the lines saying that you can see?
may the Serial boot output helps too. (you get to Serial USB ports on the DEV port, one of the is the Serial output of the SoC / Linux / bootloader running at 115200 8n1)

**Comment by W5DMH** [comment]
I can't connect to that Dev port unless the rig is already booted (with a windows box running putty). I tried to leave it connected and restart Putty at the beginning of the boot and found that Armbian is getting power from the USB-DEV port...defeats the purpose and it also does boot up Armbian that way. 
I did make a video of the boot sequence so I could see where it stopped , it stopped on "Begin: Running /scripts/init-button...done" 
Then I tried something different, instead of releasing the buttons after the backlights come on, I continued to hold it down. 
When I continue to hold down the  On/Off and the #2 button, Armbian continues to boot up all the way until I let go of the buttons...then it simply powers off like somebody unplugged the battery ....very odd behavior, thinking either I have a defect, or they changed the design. 
Even more odd,  the green power light goes off when Armbian starts booting when I boot up with #2 pressed. if I do a normal x6100 boot, the green light comes on and stays on. Did another test and booted all the way to the Armbian login holding both buttons down...released the #2 button with no effect....released the power button and immediate power off.

**Comment by W5DMH** [comment]
Success! 
So if I release the on/off button before the green light goes off, but continue to hold the #2 button...I boot up Armbian with a working radio on the internal battery!

Found this by accident trying to run on just the x6100 and change bluetooth settings while on the internal battery. If you hold the on button too long when starting, it will move to a shut down process. That is different behavior than when it is on the external power, where continuous holding down the on button does not result in an shutdown process. 

Sorry to have wasted your time, but maybe this will help others who struggle with this . 
Thanks again for your hard work, what a game changing concept!
